import { doc, getDoc, updateDoc, arrayUnion } from 'firebase/firestore';
import { db } from '../config/firebase';
import type { AnsLetterRecord, AnsLetterStatus } from '../types';

function makeId(): string {
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

/** Append an ANS letter issuance record to the student document's ansHistory array. */
export async function saveAnsLetterRecord(
  studentId: string,
  data: Omit<AnsLetterRecord, 'id' | 'status'>,
): Promise<void> {
  const record: AnsLetterRecord = { ...data, id: makeId(), status: 'sent' };
  await updateDoc(doc(db, 'students', studentId), {
    ansHistory: arrayUnion(record),
  });
}

/** Advance/change the follow-up status of a single issued letter (Sent → Parent Visited → Resolved). */
export async function updateAnsLetterStatus(
  studentId: string,
  recordId: string,
  status: AnsLetterStatus,
): Promise<void> {
  const ref = doc(db, 'students', studentId);
  const snap = await getDoc(ref);
  const history = (snap.data() as { ansHistory?: AnsLetterRecord[] } | undefined)?.ansHistory ?? [];
  const updated = history.map((r) =>
    r.id === recordId ? { ...r, status, statusUpdatedAt: new Date().toISOString() } : r,
  );
  await updateDoc(ref, { ansHistory: updated });
}

/** Permanently remove a single issued-letter record (e.g. generated by mistake). */
export async function deleteAnsLetterRecord(studentId: string, recordId: string): Promise<void> {
  const ref = doc(db, 'students', studentId);
  const snap = await getDoc(ref);
  const history = (snap.data() as { ansHistory?: AnsLetterRecord[] } | undefined)?.ansHistory ?? [];
  const updated = history.filter((r) => r.id !== recordId);
  await updateDoc(ref, { ansHistory: updated });
}

/** Read ANS letter history from the student document, sorted newest-first. */
export async function getAnsRecordsByStudent(studentId: string): Promise<AnsLetterRecord[]> {
  const snap = await getDoc(doc(db, 'students', studentId));
  const history = (snap.data() as { ansHistory?: AnsLetterRecord[] } | undefined)?.ansHistory ?? [];
  return [...history].sort((a, b) => b.issuedAt.localeCompare(a.issuedAt));
}
